name: Workflow using Actions

on: push

jobs:
  run-javascript-action:
   runs-on: ubuntu-latest
   steps:
     - name: File Listing
       run: |
         pwd
         ls
         echo $GITHUB_SHA
         echo $RUNNER_NAME
         echo $GITHUB_WORKFLOW
         echo $GITHUB_REPOSITORY
         echo "${{ github.token}}"
     - name: checkout action
       uses: actions/checkout@v2.4.0
     - name: File Listing again
       run: |
         pwd
         ls -a
     - name: first js Actions
       id: jsact
       uses: actions/hello-world-javascript-action@v1
       with: 
        who-to-greet: Manty
     - name: using output of step
       run: echo "${{ steps.jsact.outputs.time }}"
        