name: Workflow using Actions

on: push

jobs:
  run-javascript-action:
   runs-on: ubuntu-latest
   steps:
     - name: File Listing
       run: |
         pwd
         ls
     - name: first js Actions
       id: jsact
       uses: actions/hello-world-javascript-action@v1
       with: 
        who-to-greet: Manty
     - name: using output of step
       run: echo "${{ steps.jsact.outputs.time }}"
        